/* Learning, review and player-progression layer. */
const Academy={
  KEY:'chess_grandmaster_academy',
  get(){const defaults={name:'Игрок',voice:false,pieceStyle:'classic',tasks:[],lessons:[],achievements:[],games:0,wins:0,bestMove:null};try{return{...defaults,...(JSON.parse(localStorage.getItem(this.KEY))||{})}}catch(e){return defaults}},
  save(data){try{localStorage.setItem(this.KEY,JSON.stringify(data))}catch(e){}},
  profile:null,
  award(id,title,text){if(this.profile.achievements.includes(id))return;this.profile.achievements.push(id);this.save(this.profile);const toast=document.createElement('div');toast.className='academy-toast';toast.innerHTML=`<strong>✦ Достижение: ${title}</strong><span>${text}</span>`;document.body.appendChild(toast);setTimeout(()=>toast.remove(),4200)},
  speak(text){if(!this.profile.voice||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=.94;u.pitch=.92;speechSynthesis.speak(u)}catch(e){}}
};
Academy.profile=Academy.get();
document.body.dataset.pieceStyle=Academy.profile.pieceStyle||'classic';

function academyHtml(){return `
<div class="screen academy-screen" id="screen-academy">
  <div class="academy-top"><div><h1 id="academy-title">Шахматная академия</h1><p id="academy-subtitle">Учитесь думать, видеть угрозы и выигрывать красиво.</p></div><button class="btn btn-secondary" onclick="showMenu()">← В меню</button></div>
  <div id="academy-content"></div>
</div>
<div class="modal-overlay" id="modal-review"><div class="modal game-review"><div id="review-content"></div><div class="modal-buttons"><button class="btn btn-primary" onclick="closeModal('modal-review')">Понятно</button><button class="btn btn-secondary" onclick="showAcademy('profile')">Мой прогресс</button></div></div></div>`}
document.querySelector('.app-container').insertAdjacentHTML('beforeend',academyHtml());

const menuGrid=document.querySelector('#screen-menu .menu-grid');
menuGrid.insertAdjacentHTML('beforeend',`<div class="menu-card academy-card" role="button" tabindex="0" onclick="showAcademy('home')"><span class="menu-card-icon">♟</span><div class="menu-card-title">Шахматная академия</div><div class="menu-card-desc">Тренер, задачи, уроки, разбор партий и ваш личный прогресс.</div><span class="menu-card-badge academy-badge">Учиться</span></div>`);
document.querySelectorAll('.menu-card[role="button"]').forEach(card=>card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();card.click()}}));

document.querySelector('.side-panel').insertAdjacentHTML('afterbegin',`<div class="panel-card coach-card"><div class="panel-title">♟ Тренер Stockfish</div><div class="coach-state" id="coach-state"><strong>Готов помочь.</strong><br>Сделайте ход или попросите подсказку — объясню позицию человеческим языком.</div><div class="coach-actions"><button class="coach-action primary" onclick="coachHint('exact')">✦ Лучший ход</button><button class="coach-action" onclick="coachHint('soft')">◌ Мягкая подсказка</button><button class="coach-action" onclick="coachReviewPosition()">⌁ Разобрать позицию</button><button class="coach-action" onclick="openGameReview()">▤ Разбор партии</button></div><div class="coach-small"><span id="voice-status">Голос: выкл.</span><button onclick="toggleCoachVoice()">Изменить</button></div></div><div class="quick-reactions" id="quick-reactions"><button class="reaction-btn" onclick="sendReaction('👍')">👍</button><button class="reaction-btn" onclick="sendReaction('🤝')">🤝</button><button class="reaction-btn" onclick="sendReaction('🔥')">🔥</button><button class="reaction-btn" onclick="sendReaction('♟')">♟</button><button class="reaction-btn" onclick="requestRematch()">Реванш</button></div>`);

function setCoach(text){const el=document.getElementById('coach-state');if(el)el.innerHTML=text}
function coord(row,col){return String.fromCharCode(97+col)+(8-row)}
function pieceName(piece){return({p:'пешка',n:'конь',b:'слон',r:'ладья',q:'ферзь',k:'король'})[typeOf(piece)]||'фигура'}
function moveWords(move){const piece=state.board[move.from[0]][move.from[1]],target=state.board[move.to[0]][move.to[1]],name=pieceName(piece);return target?`${name[0].toUpperCase()+name.slice(1)} берёт фигуру на ${coord(move.to[0],move.to[1])}`:`${name[0].toUpperCase()+name.slice(1)} идёт на ${coord(move.to[0],move.to[1])}`}
function clearCoachMarks(){document.querySelectorAll('.coach-arrow-origin,.coach-arrow-target').forEach(el=>el.classList.remove('coach-arrow-origin','coach-arrow-target'))}
function markCoachMove(move,exact=true){clearCoachMarks();const from=document.querySelector(`.square[data-row="${move.from[0]}"][data-col="${move.from[1]}"]`);const to=document.querySelector(`.square[data-row="${move.to[0]}"][data-col="${move.to[1]}"]`);if(from)from.classList.add('coach-arrow-origin');if(exact&&to)to.classList.add('coach-arrow-target');setTimeout(clearCoachMarks,exact?3800:2500)}

function localHintMove(){
 const moves=getAllValidMoves(state.turn);if(!moves.length)return null;
 let best=moves[0],bestScore=-Infinity;
 for(const move of moves){const simulated=simulateMove(state.board,state.kingPositions,state.castling,state.enPassant,move.from,move.to,state.turn),opponent=state.turn==='white'?'black':'white';let score=evaluateBoard(simulated.board,state.turn);const victim=state.board[move.to[0]][move.to[1]];if(victim)score+=PIECE_VALUES[typeOf(victim)]*.35;if(isKingInCheck(simulated.board,simulated.kings[opponent],opponent))score+=60;if(score>bestScore){bestScore=score;best=move}}
 return best;
}
function validCoachMove(move){return!!move&&getValidMoves(move.from[0],move.from[1]).some(([row,col])=>row===move.to[0]&&col===move.to[1])}
async function coachHint(mode){
 if(state.gameOver||state.pendingPromotion){showToast('Сначала завершите текущий ход');return}if(state.gameMode==='online'){showToast('Подсказки выключены в сетевой партии — честная игра');return}if(Academy.hintBusy){showToast('Тренер уже ищет ход…');return}
 Academy.hintBusy=true;clearCoachMarks();setCoach('<strong>Тренер думает…</strong><br>Ищу практичное продолжение в этой позиции.');
 let move=null,uci='',source='Stockfish';
 try{uci=await StockfishPro.bestMove(boardToFEN(),state.difficulty||2);move=uciToMove(uci);if(!validCoachMove(move))throw Error('Некорректный ход движка')}
 catch(error){move=localHintMove();source='встроенный анализ'}
 finally{Academy.hintBusy=false}
 if(!move){setCoach('<strong>Подсказка недоступна.</strong><br>В этой позиции нет легального хода или партия уже завершена.');showToast('⚠️ Нет доступного хода');return}
 markCoachMove(move,mode==='exact');const words=moveWords(move);const piece=state.board[move.from[0]][move.from[1]],target=state.board[move.to[0]][move.to[1]];
 const why=target?'выигрывает материал и заставляет соперника реагировать.':typeOf(piece)==='k'?'делает короля безопаснее.':typeOf(piece)==='n'||typeOf(piece)==='b'?'развивает фигуру и усиливает контроль над доской.':'улучшает позицию и создаёт новую угрозу.';
 setCoach(mode==='soft'?`<strong>Мягкая подсказка</strong><br>Посмотрите на ${pieceName(piece)} на ${coord(move.from[0],move.from[1])}. Она может заметно улучшить вашу позицию.`:`<strong>Рекомендация: ${words}</strong><br>Этот ход ${why}<br><small>Источник: ${source}</small>`);Academy.profile.bestMove=uci||coord(move.from[0],move.from[1])+coord(move.to[0],move.to[1]);Academy.save(Academy.profile);Academy.speak(mode==='exact'?words:'Посмотрите на подсвеченную фигуру');showToast(`💡 ${mode==='soft'?'Посмотрите на подсвеченную фигуру':'Подсказка: '+words}`);
}

showHint=function(){coachHint('exact')}
function toggleMobilePanel(){const panel=document.querySelector('.side-panel');if(!panel)return;const expanded=panel.classList.toggle('mobile-expanded');const button=document.getElementById('mobile-panel-toggle');if(button)button.setAttribute('aria-expanded',String(expanded));if(button)button.innerHTML=expanded?'⌃ <span>Скрыть</span>':'☰ <span>Партия</span>';if(expanded)panel.scrollIntoView({behavior:'smooth',block:'nearest'})}

async function coachReviewPosition(){
 if(state.gameMode==='online'){showToast('Анализ скрыт во время сетевой партии');return}const score=evaluateBoard(state.board,state.turn)/100;let message=score>.9?'У вас материальное преимущество — не спешите, укрепите короля и фигуры.':score<-.9?'Позиция требует аккуратной защиты: ищите угрозы и не оставляйте фигуры без защиты.':'Позиция примерно равная. Развивайте фигуры, боритесь за центр и берегите короля.';setCoach(`<strong>Оценка позиции: ${score>0?'+':''}${score.toFixed(1)}</strong><br>${message}`);await coachHint('soft')}

function toggleCoachVoice(){Academy.profile.voice=!Academy.profile.voice;Academy.save(Academy.profile);document.getElementById('voice-status').textContent='Голос: '+(Academy.profile.voice?'вкл.':'выкл.');if(Academy.profile.voice)Academy.speak('Голосовой тренер включён')}
document.getElementById('voice-status').textContent='Голос: '+(Academy.profile.voice?'вкл.':'выкл.');

const academyExecute=executeMove;
executeMove=function(fromRow,fromCol,toRow,toCol,promotion){
 const piece=state.board[fromRow]?.[fromCol],captured=state.board[toRow]?.[toCol],before=state.moveHistory.length,words=captured?`${pieceName(piece)} берёт фигуру на ${coord(toRow,toCol)}`:`${pieceName(piece)} идёт на ${coord(toRow,toCol)}`;academyExecute(fromRow,fromCol,toRow,toCol,promotion);if(state.moveHistory.length===before)return;
 const last=state.moveHistory.at(-1);if(Academy.profile.voice)Academy.speak(last?.notation?.includes('#')?'Мат. Партия окончена.':last?.notation?.includes('+')?words+'. Шах.':words);
 if(state.lesson){const uci=coord(fromRow,fromCol)+coord(toRow,toCol);if(uci===state.lesson.answer){Academy.profile.tasks.push(state.lesson.id);Academy.profile.tasks=[...new Set(Academy.profile.tasks)];Academy.save(Academy.profile);Academy.award('first-task','Первый тактик','Вы решили учебную задачу.');setCoach(`<strong>Верно! ✦</strong><br>${state.lesson.success}`);showToast('✅ Отлично! Задача решена');state.lesson=null}else{setCoach(`<strong>Почти.</strong><br>${state.lesson.hint}`);showToast('💡 Подумайте ещё: '+state.lesson.hint)}}
 if(!state.gameOver&&!state.lesson&&state.gameMode!=='online'){setTimeout(()=>coachThreatCheck(),160)}
};

function coachThreatCheck(){
 const side=state.turn,opponent=side==='white'?'black':'white',moves=getAllValidMoves(side);let threat=null;for(const move of moves){const target=state.board[move.to[0]][move.to[1]];if(target&&isOwnPiece(target,opponent)&&PIECE_VALUES[typeOf(target)]>=320){threat={move,target};break}}if(threat){const square=coord(threat.move.to[0],threat.move.to[1]);setCoach(`<strong>Внимание: возможна потеря фигуры.</strong><br>Соперник может забрать вашу ${pieceName(threat.target)} на ${square}. Проверьте её защиту.`)}}

function decodeFEN(fen){
 const [layout,turn,rights,ep,half,full]=fen.split(' ');const rows=layout.split('/');state.board=rows.map(row=>{const out=[];for(const char of row){if(/\d/.test(char))out.push(...Array(Number(char)).fill(null));else out.push(char)}return out});state.turn=turn==='b'?'black':'white';state.castling={white:{kingside:rights.includes('K'),queenside:rights.includes('Q')},black:{kingside:rights.includes('k'),queenside:rights.includes('q')}};state.enPassant=ep&&ep!=='-'?[8-Number(ep[1]),ep.charCodeAt(0)-97]:null;state.halfmove=Number(half)||0;state.fullmove=Number(full)||1;state.kingPositions={white:[0,0],black:[0,0]};for(let r=0;r<8;r++)for(let c=0;c<8;c++){if(state.board[r][c]==='K')state.kingPositions.white=[r,c];if(state.board[r][c]==='k')state.kingPositions.black=[r,c]};state.moveHistory=[];state.capturedPieces={white:[],black:[]};state.lastMove=null;state.gameOver=false;state.positionHistory=[positionKey()];if(state.timerInterval){clearInterval(state.timerInterval);state.timerInterval=null}}
const TASKS=[
 {id:'mate-one',title:'Мат в один ход',meta:'Найдите немедленное завершение партии',fen:'7k/6pp/8/7Q/8/8/6PP/6K1 w - - 0 1',answer:'h5e8',success:'Ферзь перекрывает королю все пути. Это чистый мат.',hint:'Посмотрите на диагональ ферзя к восьмой горизонтали.'},
 {id:'fork-queen',title:'Вилка на ферзя',meta:'Выиграйте самую ценную фигуру',fen:'4k3/8/8/3q4/8/2N5/8/4K3 w - - 0 1',answer:'c3d5',success:'Конь забирает ферзя. Всегда ищите прыжки коня на ценные фигуры.',hint:'Конь на c3 может прыгнуть на клетку с ферзём.'},
 {id:'rook-mate',title:'Ладейная сила',meta:'Поставьте мат ладьёй',fen:'7k/6pp/8/8/8/8/6PP/6RK w - - 0 1',answer:'g1g8',success:'Ладья контролирует всю горизонталь — королю некуда бежать.',hint:'Ладья умеет мгновенно атаковать по линии.'}
];
function startTask(id){const task=TASKS.find(x=>x.id===id);if(!task)return;decodeFEN(task.fen);state.gameMode='lesson';state.playerColor=state.turn;state.lesson=task;document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('screen-game').classList.add('active');renderBoard();updateUI();setCoach(`<strong>Задача: ${task.title}</strong><br>${task.meta}. ${task.hint}`);showToast('♟ Учебная задача загружена')}

function academyHome(){return `<div class="academy-grid"><button class="academy-tile" onclick="showAcademy('tasks')"><i class="academy-tile-icon">✦</i><strong>Задачи дня</strong><span>Мат, вилка и тактика — короткие практические позиции.</span></button><button class="academy-tile" onclick="showAcademy('lessons')"><i class="academy-tile-icon">◫</i><strong>Уроки</strong><span>Освойте развитие, защиту короля и основы хорошего плана.</span></button><button class="academy-tile" onclick="showAcademy('history')"><i class="academy-tile-icon">♜</i><strong>Классика</strong><span>Изучайте знаменитые шахматные мотивы через живые позиции.</span></button><button class="academy-tile" onclick="showAcademy('profile')"><i class="academy-tile-icon">◎</i><strong>Мой прогресс</strong><span>Достижения, решённые задачи и личная статистика.</span></button><button class="academy-tile" onclick="showAcademy('style')"><i class="academy-tile-icon">◇</i><strong>Стиль игры</strong><span>Выберите внешний вид фигур и комфортный формат доски.</span></button><button class="academy-tile" onclick="showAcademy('how')"><i class="academy-tile-icon">?</i><strong>Как учиться</strong><span>Понятный путь от первых ходов к уверенной игре.</span></button></div>`}
function tasksPage(){return `<div class="task-list">${TASKS.map((t,i)=>`<button class="task-row" onclick="startTask('${t.id}')"><i class="row-icon">${i===0?'♛':i===1?'♞':'♜'}</i><span class="row-text"><strong>${t.title}</strong><span>${t.meta}</span></span><b class="row-mark">${Academy.profile.tasks.includes(t.id)?'✓':'Играть'}</b></button>`).join('')}</div>`}
function lessonsPage(){const lessons=[['opening','Первые 10 ходов','Развивайте лёгкие фигуры, боритесь за центр, не выводите ферзя слишком рано.'],['king','Безопасность короля','Рокировка — не роскошь: она убирает короля из центра и вводит ладью в игру.'],['tactics','Тактическое зрение','Перед каждым ходом спрашивайте: шахи, взятия, угрозы — у меня и у соперника.'],['endgame','Эндшпиль','Король в окончании становится активной фигурой, а пешка — потенциальным ферзём.']];return `<div class="lesson-list">${lessons.map((l,i)=>`<button class="lesson-row" onclick="readLesson('${l[0]}')"><i class="row-icon">${['①','②','③','④'][i]}</i><span class="row-text"><strong>${l[1]}</strong><span>${l[2]}</span></span><b class="row-mark">Читать</b></button>`).join('')}</div>`}
function historyPage(){const positions=[['Мотив Морфи','Развитие фигур важнее охоты за пешками. Найдите решающий ход в учебной позиции.','mate-one'],['Тактика Ласкера','Конь способен неожиданно менять ход всей партии.','fork-queen'],['Ладейный финал','Открытая линия для ладьи часто решает партию.','rook-mate']];return `<div class="history-list-pro">${positions.map(p=>`<button class="history-row" onclick="startTask('${p[2]}')"><i class="row-icon">♜</i><span class="row-text"><strong>${p[0]}</strong><span>${p[1]}</span></span><b class="row-mark">Открыть</b></button>`).join('')}</div>`}
function profilePage(){const p=Academy.profile,all=[['first-task','✦','Первый тактик'],['first-win','♛','Первая победа'],['five-games','♟','Пять партий'],['online','◎','Сетевая партия']];return `<div class="profile-head"><div class="profile-avatar">♟</div><div><div class="profile-name">${p.name}</div><div class="profile-sub">Сыграно партий: ${p.games||0} · Решено задач: ${p.tasks.length}</div><div class="progress-meter"><i style="width:${Math.min(100,(p.tasks.length/Math.max(1,TASKS.length))*100)}%"></i></div></div><button class="profile-edit" onclick="editProfileName()">Изменить имя</button></div><div class="panel-card" style="margin-top:12px"><div class="panel-title">Коллекция достижений</div><div class="achievement-grid">${all.map(a=>`<div class="achievement ${p.achievements.includes(a[0])?'unlocked':''}"><b>${a[1]}</b>${a[2]}</div>`).join('')}</div></div>`}
function stylePage(){return `<div class="panel-card"><div class="panel-title">Набор фигур</div><div class="piece-style-row">${[['classic','Классика'],['modern','Современный'],['outline','Контур']].map(([id,name])=>`<button class="piece-style ${Academy.profile.pieceStyle===id?'active':''}" onclick="setPieceStyle('${id}')">${name}</button>`).join('')}</div><p style="font-size:.73rem;color:var(--text-secondary);line-height:1.5;margin-top:14px">Темы доски уже доступны в настройках игры. Здесь можно быстро выбрать характер самих фигур.</p></div>`}
function howPage(){return `<div class="panel-card" style="line-height:1.7;color:var(--text-secondary);font-size:.82rem"><strong style="color:var(--text-primary)">Самый быстрый путь к уверенному шахматному мышлению:</strong><ol style="padding-left:20px;margin-top:9px"><li>Решайте одну-две задачи перед партией.</li><li>В дебюте развивайте фигуры и рокируйтесь.</li><li>Перед каждым ходом проверяйте шахи, взятия и угрозы.</li><li>После партии открывайте разбор и находите один главный урок.</li></ol></div>`}
function showAcademy(section='home'){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('screen-academy').classList.add('active');const titles={home:['Шахматная академия','Учитесь думать, видеть угрозы и выигрывать красиво.'],tasks:['Задачи дня','Короткие позиции, которые тренируют тактическое зрение.'],lessons:['Уроки','Понятная теория без перегруженных вариаций.'],history:['Классические мотивы','Учимся на идеях великих партий и позициях.'],profile:['Мой прогресс','Ваш путь в шахматах — шаг за шагом.'],style:['Стиль игры','Сделайте доску своей.'],how:['Путь игрока','Небольшая привычка каждый день даёт большой рост.']};document.getElementById('academy-title').textContent=titles[section][0];document.getElementById('academy-subtitle').textContent=titles[section][1];document.getElementById('academy-content').innerHTML=({home:academyHome,tasks:tasksPage,lessons:lessonsPage,history:historyPage,profile:profilePage,style:stylePage,how:howPage}[section]||academyHome)()}
function readLesson(id){Academy.profile.lessons=[...new Set([...Academy.profile.lessons,id])];Academy.save(Academy.profile);const texts={opening:'В начале партии выведите коней и слонов, захватите центр пешками и не делайте один и тот же ход фигурой много раз без причины.',king:'Если центр может открыться, короля надо убрать в безопасность. Рокировка делает именно это и одновременно активирует ладью.',tactics:'У хорошего шахматного хода обычно есть конкретика. Всегда сначала смотрите: можно ли поставить шах, что можно взять и какая фигура остаётся без защиты.',endgame:'Когда фигур меньше, король перестаёт прятаться. Ведите его к центру, поддерживайте пешки и считайте темп до превращения.'};setCoach(`<strong>Урок</strong><br>${texts[id]}`);showToast('📘 Урок открыт в панели тренера')}
function editProfileName(){const name=prompt('Как вас называть в игре?',Academy.profile.name);if(name&&name.trim()){Academy.profile.name=name.trim().slice(0,24);Academy.save(Academy.profile);showAcademy('profile')}}
function setPieceStyle(style){Academy.profile.pieceStyle=style;Academy.save(Academy.profile);document.body.dataset.pieceStyle=style;renderBoard();showAcademy('style')}

function reviewSummary(){const history=state.moveHistory||[],captures=history.filter(m=>m.isCapture).length,checks=history.filter(m=>/[+#]$/.test(m.notation||'')).length;return{moves:history.length,captures,checks,tip:state.gameOver?'Посмотрите на ход перед решающим изменением позиции: именно там чаще всего находится главный урок.':'Закончите партию, чтобы получить итоговый разбор.'}}
function openGameReview(){const data=reviewSummary();document.getElementById('review-content').innerHTML=`<div class="review-head"><div class="review-score">${data.moves}</div><div class="modal-title">полуходов в партии</div></div><div class="review-insight"><strong>Главный совет</strong><br>${data.tip}</div><div class="review-list"><div class="review-item">♟ <span>Взятий в партии: ${data.captures}</span></div><div class="review-item">✦ <span>Шахов и матовых угроз: ${data.checks}</span></div><div class="review-item">⌁ <span>Следующий шаг: запросите «Лучший ход» в ключевой позиции и сравните со своим решением.</span></div></div>`;openModal('modal-review')}

const academyEndGame=endGame;
endGame=function(reason,winner){const mode=state.gameMode,moves=state.moveHistory.length;academyEndGame(reason,winner);if(mode==='ai'||mode==='pvp'){Academy.profile.games=(Academy.profile.games||0)+1;if((mode==='ai'&&winner===state.playerColor)||reason==='checkmate'&&mode==='pvp')Academy.profile.wins=(Academy.profile.wins||0)+1;Academy.save(Academy.profile);if(Academy.profile.games>=1)Academy.award('first-win','Первая завершённая партия','Продолжайте — каждая партия учит новому.');if(Academy.profile.games>=5)Academy.award('five-games','Пять партий','Регулярность превращается в силу.')}setTimeout(()=>{const modal=document.getElementById('modal-gameover');if(modal&&modal.classList.contains('active')&&!document.getElementById('btn-open-review')){const btn=document.createElement('button');btn.id='btn-open-review';btn.className='btn btn-secondary';btn.textContent='▤ Разбор партии';btn.onclick=openGameReview;modal.querySelector('.modal-buttons').appendChild(btn)}},430)};

function sendReaction(emoji){if(state.gameMode!=='online'||!state.online?.conn?.open){showToast('Реакции доступны в сетевой партии');return}state.online.conn.send({type:'reaction',emoji});showReaction(emoji)}
function showReaction(emoji){const node=document.createElement('div');node.className='reaction-float';node.textContent=emoji;node.style.left=(window.innerWidth/2-12)+'px';node.style.top=(window.innerHeight*.55)+'px';document.body.appendChild(node);setTimeout(()=>node.remove(),1550)}
function requestRematch(){if(state.gameMode!=='online'||!state.online?.conn?.open){showToast('Реванш доступен после сетевой партии');return}state.online.conn.send({type:'rematch-request'});showToast('♟ Предложение реванша отправлено')}
function restartOnlineMatch(){initBoard();state.gameMode='online';state.gameOver=false;closeModal('modal-gameover');renderBoard();updateUI();showToast('♟ Реванш начался')}
const academyOnlineData=handleOnlineData;
handleOnlineData=function(data){if(data?.type==='reaction'){showReaction(data.emoji||'♟');return}if(data?.type==='rematch-request'){if(confirm('Соперник предлагает реванш. Начать новую партию?')){state.online.conn.send({type:'rematch-accept'});restartOnlineMatch()}return}if(data?.type==='rematch-accept'){restartOnlineMatch();return}academyOnlineData(data)};
const academyUpdate=updateUI;
updateUI=function(){academyUpdate();const reactions=document.getElementById('quick-reactions');if(reactions)reactions.classList.toggle('visible',state.gameMode==='online'&&state.onlineConnected)};

/* Re-open the landing screen after the academy creates its extra screen. */
showMenu();

/* Academy is loaded as a separate file; expose actions used by inline controls. */
Object.assign(window,{coachHint,coachReviewPosition,toggleCoachVoice,openGameReview,sendReaction,requestRematch,showAcademy,startTask,readLesson,editProfileName,setPieceStyle,toggleMobilePanel,showHint});
